### ISSUE TITLE
[Bug] Scroll not working anymore with Niftis since version 1.47.0 

### ISSUE THREAD

**Issue by CYB3RL1F3** [cornerstonejs/cornerstone3D#1013]
### Describe the Bug

getTargetVolumeAndSpacingInNormalDir.ts:74 Uncaught TypeError: Cannot destructure property 'uid' of 'volumeActors[imageVolumeIndex]' as it is undefined.
    at getTargetVolumeAndSpacingInNormalDir (getTargetVolumeAndSpacingInNormalDir.ts:74:18)
    at getVolumeSliceRangeInfo (getVolumeSliceRangeInfo.ts:30:5)
    at Object.getVolumeViewportScrollInfo (getVolumeViewportScrollInfo.ts:18:5)
    at scrollVolume (scroll.ts:63:13)
    at scroll (scroll.ts:46:5)
    at StackScrollMouseWheelTool.mouseWheelCallback (StackScrollToolMouseWheelTool.ts:40:5)
    at customCallbackHandler (customCallbackHandler.ts:72:28)
    at triggerEvent (triggerEvent.ts:37:13)
    at HTMLDivElement.wheelListener 
    
      
      

### Steps to Reproduce

Add a nifti and create a derived volume

### The current behavior

Scroll is blocked.
It was workign well before.

### The expected behavior

To work well like in the version 1.46

### OS

Mac OS

### Node version

20.0.0

### Browser

Chrome

**Comment by CYB3RL1F3** [comment]
Hello,
Is it fixed? Could we upgrade?

**Comment by sedghi** [comment]
it is fixed now, can you check?
