### ISSUE TITLE
[Bug] Uncaught (in promise) TypeError: Cannot destructure property 'pixelRepresentation' of 'metaData_exports.get(...)' as it is undefined.

### ISSUE THREAD

**Issue by hiren3897** [cornerstonejs/cornerstone3D#1253]
### Describe the Bug

I am trying to load CT Dicom using Volume Loaders, but I come up with the error mentioned in the title.

ERROR:
```
@cornerstonejs_streaming-image-volume-loader.js?v=826969f1:37848 Uncaught (in promise) TypeError: Cannot destructure property 'pixelRepresentation' of 'metaData_exports.get(...)' as it is undefined.
    at makeVolumeMetadata (@cornerstonejs_streaming-image-volume-loader.js?v=826969f1:37848:11)
    at Object.generateVolumePropsFromImageIds (@cornerstonejs_streaming-image-volume-loader.js?v=826969f1:38201:26)
    at getStreamingImageVolume (@cornerstonejs_streaming-image-volume-loader.js?v=826969f1:65270:119)
    at cornerstoneStreamingImageVolumeLoader (@cornerstonejs_streaming-image-volume-loader.js?v=826969f1:65293:39)
    at loadVolumeFromVolumeLoader (chunk-SZQ6NIV2.js?v=826969f1:36665:28)
    at Object.createAndCacheVolume (chunk-SZQ6NIV2.js?v=826969f1:36700:22)
    at loadVolume (cornerstone.ts:52:5)
    at updateViewportAndImage (CornerstoneViewer.tsx:134:7)
    at CornerstoneViewer.tsx:167:3
    at commitHookEffectListMount (chunk-KMBCB5BM.js?v=826969f1:16445:34)
```

### Steps to Reproduce

I will be providing files that play main roles in loading the DICOM in the viewport
```ts
// initCornerstone.ts
import { init as csRenderInit, volumeLoader } from "@cornerstonejs/core";
import * as cornerstone from "@cornerstonejs/core";
import cornerstoneDICOMImageLoader from "@cornerstonejs/dicom-image-loader";
import { cornerstoneStreamingImageVolumeLoader } from "@cornerstonejs/streaming-image-volume-loader";
import {
  init as csToolsInit,
  PanTool,
  WindowLevelTool,
  StackScrollMouseWheelTool,
  ZoomTool,
  addTool,
} from "@cornerstonejs/tools";
import * as cornerstoneTools from "@cornerstonejs/tools";
import dicomParser from "dicom-parser";

import BoxTool from "cornerstone/tools/BoxTool";
import MeasuresTool from "cornerstone/tools/MeasuresTool";

const TOKEN = import.meta.env.VITE_GCLOUD;

window.cornerstone = cornerstone;
window.cornerstoneTools = cornerstoneTools;
cornerstone.init();
cornerstoneTools.init();

const { preferSizeOverAccuracy, useNorm16Texture } = cornerstone.getConfiguration().rendering;

function initCornerstoneDICOMImageLoader() {
  cornerstoneDICOMImageLoader.external.cornerstone = cornerstone;
  cornerstoneDICOMImageLoader.external.dicomParser = dicomParser;

  cornerstoneDICOMImageLoader.configure({
    useWebWorkers: true,
    decodeConfig: {
      convertFloatPixelDataToInt: false,
      use16BitDataType: preferSizeOverAccuracy || useNorm16Texture,
    },
    beforeSend(xhr: any) {
      // Add custom headers here (e.g. auth tokens)
      xhr.setRequestHeader("Authorization", `Bearer ${TOKEN}`);
    },
  });

  let maxWebWorkers = 1;

  if (navigator.hardwareConcurrency) {
    maxWebWorkers = Math.min(navigator.hardwareConcurrency, 7);
  }

  const config = {
    maxWebWorkers,
    startWebWorkersOnDemand: false,
    taskConfiguration: {
      decodeTask: {
        initializeCodecsOnStartup: false,
        strict: false,
      },
    },
  };

  cornerstoneDICOMImageLoader.webWorkerManager.initialize(config);
}

function initVolumeLoader() {
  volumeLoader.registerVolumeLoader("cornerstoneStreamingImageVolume", cornerstoneStreamingImageVolumeLoader as any);
}

const { calibratedPixelSpacingMetadataProvider, genericMetadataProvider } = cornerstone.utilities;

function initProviders() {
  cornerstone.metaData.addProvider(
    calibratedPixelSpacingMetadataProvider.get.bind(calibratedPixelSpacingMetadataProvider),
    11000,
  );

  cornerstone.metaData.addProvider(genericMetadataProvider.get.bind(genericMetadataProvider), 10000);
}

let toolsAlreadyAdded = false;

export const initCornerstone = async () => {
  initProviders();
  initCornerstoneDICOMImageLoader();
  initVolumeLoader();
  await csRenderInit();
  csToolsInit();

  if (!toolsAlreadyAdded) {
    addTool(PanTool);
    addTool(WindowLevelTool);
    addTool(StackScrollMouseWheelTool);
    addTool(ZoomTool);
    addTool(MeasuresTool);
    addTool(BoxTool);

    toolsAlreadyAdded = true;
  }
};
```

```ts
// utils/createImageIdsAndCacheMetaData
export async function createImageIdsAndCacheMetaData({
  studyInstanceUID,
  seriesInstanceUID,
  sopInstanceUID = null,
}: ICreateImageIdsAndCacheMetaData): Promise<string[]> {
  const studySearchOptions = {
    studyInstanceUID,
    seriesInstanceUID,
  };

  let instances = await dicomWebClient.retrieveSeriesMetadata(studySearchOptions);

  // if sop instance is provided we should filter the instances to only include the one we want
  if (sopInstanceUID) {
    instances = instances.filter(instance => {
      return instance[DicomTags.SOP_INSTANCE_UID]?.Value?.[0] === sopInstanceUID;
    });
  }

  const modality = instances[0][DicomTags.MODALITY]?.Value?.[0];
  console.log({ modality });

  let imageIds = instances.map(instanceMetaData => {
    const SeriesInstanceUID = instanceMetaData[DicomTags.SERIES_INSTANCE_UID]?.Value?.[0];
    const SOPInstanceUIDToUse = sopInstanceUID || instanceMetaData[DicomTags.SOP_INSTANCE_UID]?.Value?.[0];

    const prefix = "wadors: ";

    const imageId = `${
      prefix + dicomWebClient.baseURL
    }/studies/${studyInstanceUID}/series/${SeriesInstanceUID}/instances/${SOPInstanceUIDToUse}/frames/1`;

    cornerstoneDICOMImageLoader.wadors.metaDataManager.add(imageId, instanceMetaData);
    return imageId;
  });

  // if the image ids represent multiframe information, creates a new list with one image id per frame
  // if not multiframe data available, just returns the same list given
  imageIds = convertMultiframeImageIds(imageIds);

  imageIds.forEach(imageId => {
    let instanceMetaData = cornerstoneDICOMImageLoader.wadors.metaDataManager.get(imageId);

    // It was using JSON.parse(JSON.stringify(...)) before but it is 8x slower
    instanceMetaData = removeInvalidTags(instanceMetaData);
    console.log({ instanceMetaData });

    if (instanceMetaData) {
      // Add calibrated pixel spacing
      const metadata = DicomMetaDictionary.naturalizeDataset(instanceMetaData);
      const pixelSpacing = getPixelSpacingInformation(metadata);
      if (pixelSpacing) {
        calibratedPixelSpacingMetadataProvider.add(imageId, {
          rowPixelSpacing: parseFloat(pixelSpacing.PixelSpacing ? pixelSpacing.PixelSpacing[0] : pixelSpacing[0]),
          columnPixelSpacing: parseFloat(pixelSpacing.PixelSpacing ? pixelSpacing.PixelSpacing[0] : pixelSpacing[1]),
          type: pixelSpacing.type ? pixelSpacing.type : Enums.CalibrationTypes.NOT_APPLICABLE,
        });
      }

      console.log("imagePixelModule before", metaData.get("imagePixelModule", imageId));
      genericMetadataProvider.add(imageId, {
        type: "imagePixelModule",
        metadata: metaData.get("imagePixelModule", imageId),
      });
    }
  });

  return imageIds;
}
```

This is a ConerstoneViewer.tsx that loads the viewport with imageIds
```tsx
// CornerstoneViewer.tsx
import { useEffect, useRef, useState } from "react";

import { volumeLoader } from "@cornerstonejs/core";
import { useParams } from "react-router-dom";
import { styled } from "styled-components";

import { useCachedSerie } from "api/dicomStudy";
import { createImageIdsAndCacheMetaData } from "api/dicomStudyHelpers";
import LoadingFallback from "components/Shared/LoadingFallback";
// import { useMilvueUser } from "contexts/userContext";
// import { useViewerCtx, useAnnotationCtx } from "contexts/viewerContext";
import { useCanvasCtx } from "contexts/canvasContext";
import { UpdateImageIdEvent } from "cornerstone/events/UpdateImageIdEvent";
import { RENDERING_ENGINE_ID } from "cornerstone/types/const";
// import { buildBoxsForCornerstoneViewport } from "cornerstone/utils/buildSmartUrgence";
// import { buildMeasuresForCornerstoneViewport } from "cornerstone/utils/buildSmartXpert";
// import { useMilvueSelector } from "store";
// import { Image } from "types/study";
import { enableViewport, getCornerstoneViewport, loadVolume } from "utils/cornerstone";

// import { getCurrentImageAnnotations } from "../utils";

interface ICornerstoneViewportProps {
  viewportId: string;
  toggleViewSelectedOnly: () => void;
}

const Container = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  position: absolute;
  right: 0;
  left: 0;
  top: 0;
  bottom: 0;
  margin: auto;
  background: #1c232c;
  z-index: 1;
`;

const CornerstoneViewport = ({ viewportId, toggleViewSelectedOnly }: ICornerstoneViewportProps) => {
  const elementRef = useRef<HTMLDivElement>(null);

  const { studyId: studyInstanceUID } = useParams<{ studyId: string }>();

  const [isImageLoaded, setIsImageLoaded] = useState<boolean>(false);
  const [imageIds, setImageIds] = useState<string[]>([]);
  const canvasState = useCanvasCtx();

  const currentSerie = useCachedSerie(studyInstanceUID, canvasState.selected);

  // const viewerState = useViewerCtx();
  // const { user } = useMilvueUser();
  // const userAnnotations = useAnnotationCtx(currentSerie.seriesInstanceUID);
  // const productMode = useMilvueSelector(state => state.mode);

  useEffect(() => {
    let isCancelled = false;
    if (!studyInstanceUID) return;

    const fetchStudyImageIds = async () => {
      try {
        // const imids = await createStudyImageIds(studyInstanceUID);

        // console.log({ imids });

        if (currentSerie) {
          const ids = await createImageIdsAndCacheMetaData({
            studyInstanceUID,
            seriesInstanceUID: currentSerie?.seriesInstanceUID,
            sopInstanceUID: null,
          });
          console.log({ ids });

          if (!isCancelled) {
            setImageIds(ids);
          }
        }
      } catch (error) {
        if (!isCancelled) {
          console.error("Failed to fetch thumbnail", error);
          setImageIds([]);
        }
      }
    };

    fetchStudyImageIds();

    return () => {
      isCancelled = true;
    };
  }, [currentSerie, studyInstanceUID, viewportId]);

  useEffect(() => {
    if (!currentSerie) return;

    const dispatchUpdateImageId = () => {
      const updateImageIdEvent = new UpdateImageIdEvent({ imageId: currentSerie.seriesInstanceUID });
      window.dispatchEvent(updateImageIdEvent);
    };

    dispatchUpdateImageId();
  }, [currentSerie]);

  // const {
  //   data: { sourceState },
  // } = viewerState;

  // const { source } = sourceState;

  useEffect(() => {
    const element = elementRef.current;
    // This doesn't seem to happen, just here for typing the effect won't rerender anyway
    if (!element) return;

    // const annotations =
    //   source === user.id && userAnnotations !== null
    //     ? userAnnotations.annotations
    //     : getCurrentImageAnnotations(image, source);

    const updateViewportAndImage = async () => {
      if (!currentSerie) return;
      if (currentSerie.modality !== "CT") {
        enableViewport(viewportId, element);
      } else {
        await loadVolume(
          `cornerstoneStreamingImageVolume:${currentSerie.seriesInstanceUID}_volume`,
          imageIds,
          viewportId,
          element,
        );
      }

      const newViewport = getCornerstoneViewport(viewportId, RENDERING_ENGINE_ID);
      console.log({ newViewport });
      const currentImageIds = imageIds.filter(imageId => imageId.includes(currentSerie.seriesInstanceUID));

      if (newViewport) {
        if (currentSerie.modality === "CT") {
          // newViewport.render();
          setIsImageLoaded(true);
          return;
        }

        const loadedImageIds = newViewport.getImageIds();
        if (!loadedImageIds.includes(currentImageIds[0])) {
          setIsImageLoaded(false);

          await newViewport.setStack(currentImageIds);
          newViewport.render();

          setIsImageLoaded(true);
        }
        // if (annotations) {
        //   if (productMode === "smartxpert") {
        //     buildMeasuresForCornerstoneViewport({ annotations, viewportId, imageId: image.id });
        //   } else {
        //     buildBoxsForCornerstoneViewport({ annotations, viewportId });
        //   }
        // }
      }
    };

    updateViewportAndImage();
  }, [currentSerie, imageIds, viewportId, currentSerie?.modality]);

  return (
    <>
      {!isImageLoaded && (
        <Container>
          <LoadingFallback />
        </Container>
      )}
      <div
        ref={elementRef}
        onContextMenu={e => e.preventDefault()}
        style={{ height: `100%`, width: `100%` }}
        id={viewportId}
        className="cornerstone-element"
        onDoubleClick={toggleViewSelectedOnly}
      />
    </>
  );
};

export default CornerstoneViewport;
```

This files have the methods to create Viewports and Volumes 
```ts
// cornerstone.ts
import { Enums, Types, getRenderingEngine, volumeLoader, setVolumesForViewports, metaData } from "@cornerstonejs/core";

import { CORNERSTONE_TOOLS, RENDERING_ENGINE_ID } from "cornerstone/types/const";
import { createViewportTools } from "cornerstone/utils/tools";

export const getCornerstoneViewport = (viewportId: string, renderingEngineId: string) => {
  const renderingEngine = getRenderingEngine(renderingEngineId);

  if (!renderingEngine) {
    return null;
  }

  const viewport = renderingEngine.getViewport(viewportId);

  if (!viewport) {
    return null;
  }
  return viewport as Types.IStackViewport;
};

export const enableViewport = (viewportId: string, element: HTMLDivElement) => {
  const renderingEngine = getRenderingEngine(RENDERING_ENGINE_ID);
  if (!renderingEngine) return;

  const viewportInput: Types.PublicViewportInput = {
    type: Enums.ViewportType.STACK,
    viewportId,
    defaultOptions: {
      background: [28 / 255, 35 / 255, 44 / 255],
      displayArea: {
        imageArea: [1, 1],
      },
    },
    element,
  };

  const existingViewport = renderingEngine.getViewport(viewportId);

  if (existingViewport && existingViewport.element === element) return;

  renderingEngine.enableElement(viewportInput);

  createViewportTools(viewportId, CORNERSTONE_TOOLS);
};

export const loadVolume = async (volumeId: string, imageIds: string[], viewportId: string, element: HTMLDivElement) => {
  const renderingEngine = getRenderingEngine(RENDERING_ENGINE_ID);
  if (!renderingEngine || !imageIds || !imageIds.length) return;

  // Define a volume in memory
  const volume = await volumeLoader.createAndCacheVolume(volumeId, {
    imageIds,
  });

  const volumeViewportInput: Types.PublicViewportInput = {
    type: Enums.ViewportType.ORTHOGRAPHIC,
    viewportId,
    defaultOptions: {
      background: [28 / 255, 35 / 255, 44 / 255],
      displayArea: {
        imageArea: [1, 1],
      },
      // orientation: Enums.OrientationAxis.SAGITTAL,
    },
    element,
  };

  const existingViewport = renderingEngine.getViewport(viewportId);

  if (existingViewport && existingViewport.element === element) return;

  renderingEngine.enableElement(volumeViewportInput);

  createViewportTools(viewportId, CORNERSTONE_TOOLS);
  console.log(imageIds);

  console.log("imagePixelModule after", metaData.get("imagePixelModule", imageIds[0]));

  // Set the volume to load
  await volume.load();

  setVolumesForViewports(renderingEngine, [{ volumeId }], [volumeId]);
};
```

Can you please help me to resolve this error?
I have followed the perfect guidelines, following the official documents on the internet, to integrate the volume loader, but I still have the error.

I tried to mannualy add the "imagePixelModule" in genericMetadataProvider but it also doesnt work

### The current behavior

It loads all other 2D dicoms, like DX for example but fails on CT Volume

##### CT Image selected

![Screenshot from 2024-05-16 17-52-48](https://github.com/cornerstonejs/cornerstone3D/assets/59652404/3ec8e246-9ffc-47ba-8569-baf3a1a3fb79)

##### DX Image selected

![Screenshot from 2024-05-16 17-41-13](https://github.com/cornerstonejs/cornerstone3D/assets/59652404/35ca5276-9a7e-408f-85d5-e2b756d4f8e9)

#### ImagePixelModule of the imageId (from the console) which means it exist so the error should not be thrown!!!
```json
{
    "samplesPerPixel": 1,
    "photometricInterpretation": "MONOCHROME2",
    "rows": 512,
    "columns": 512,
    "bitsAllocated": 16,
    "bitsStored": 12,
    "highBit": 11,
    "pixelRepresentation": 0
}
```

### The expected behavior

To load the CT DICOM in Volume Loader :) 

### OS

Ubuntu 22.04

### Node version

v21.4.0

### Browser

Google Chrome 124.0.6367.201

**Comment by tonitomystery** [comment]
try older versions of @cornerstonejs/dicom-image-loader
