### ISSUE TITLE
Build core example error [Bug] 

### ISSUE THREAD

**Issue by 1009058470** [cornerstonejs/cornerstone3D#1314]
### Describe the Bug

When i run `yarn run example core` to try to run example, there make this error here 
```
D:\cornerstone3D\cornerstone3D-1.77.12\cornerstone3D-1.77.12\utils\ExampleRunner\example-runner-cli.js:36
  return str.replace(/\\\\/g, '/');
             ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at validPath (D:\cornerstone3D\cornerstone3D-1.77.12\cornerstone3D-1.77.12\utils\ExampleRunner\example-runner-cli.js:36:14)
    at run (D:\cornerstone3D\cornerstone3D-1.77.12\cornerstone3D-1.77.12\utils\ExampleRunner\example-runner-cli.js:276:7)
    at Object.<anonymous> (D:\cornerstone3D\cornerstone3D-1.77.12\cornerstone3D-1.77.12\utils\ExampleRunner\example-runner-cli.js:255:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)      
    at node:internal/main/run_main_module:22:47
```

### Steps to Reproduce

`yarn install`
`yarn run example core` 

### The current behavior

get error like blow
```
D:\cornerstone3D\cornerstone3D-1.77.12\cornerstone3D-1.77.12\utils\ExampleRunner\example-runner-cli.js:36
  return str.replace(/\\\\/g, '/');
             ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at validPath (D:\cornerstone3D\cornerstone3D-1.77.12\cornerstone3D-1.77.12\utils\ExampleRunner\example-runner-cli.js:36:14)
    at run (D:\cornerstone3D\cornerstone3D-1.77.12\cornerstone3D-1.77.12\utils\ExampleRunner\example-runner-cli.js:276:7)
    at Object.<anonymous> (D:\cornerstone3D\cornerstone3D-1.77.12\cornerstone3D-1.77.12\utils\ExampleRunner\example-runner-cli.js:255:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)      
    at node:internal/main/run_main_module:22:47
```

### The expected behavior

no error when build core example

### OS

windows 11 23H2

### Node version

16.20.2

### Browser

CHrome 100

![image](https://github.com/cornerstonejs/cornerstone3D/assets/30902531/ef88c6f4-50f6-490c-92e0-842cd34cc404)

**Comment by jlopes90** [comment]
try `yarn example core`

**Comment by jlopes90** [comment]
There is no `core` example.

**Comment by 1009058470** [comment]
> There is no example `core`.

i find that [here](https://www.cornerstonejs.org/docs/tutorials/examples#run-examples-locally)
```
Run Examples Locally
You can also run each example locally. It should be noted that Cornerstone3D is a monorepo and contains three packages (core, tools, streaming-image-volume). Examples for each of these packages are included in the examples directory inside each package. You can run each example by using its name as an argument to the example script. For instance, It should be noted that the example name is not case sensitive, and even it can suggest the name of the example you are looking for if you make a typo.


```

**Comment by jlopes90** [comment]
![image](https://github.com/cornerstonejs/cornerstone3D/assets/50026015/120c657f-17cf-4657-af68-6f4d5006ae07)

For example, `yarn example stackBasic` or `yarn example stackApi`

**Comment by jlopes90** [comment]
Here are the examples:
[Adapters Examples](https://github.com/cornerstonejs/cornerstone3D/tree/main/packages/adapters/examples)
[Core Examples](https://github.com/cornerstonejs/cornerstone3D/tree/main/packages/core/examples)
[DicomImageLoader Examples](https://github.com/cornerstonejs/cornerstone3D/tree/main/packages/dicomImageLoader/examples)
[NiftiVolumeLoader Examples](https://github.com/cornerstonejs/cornerstone3D/tree/main/packages/nifti-volume-loader/examples)
[StreamingImageVolumeLoader Examples](https://github.com/cornerstonejs/cornerstone3D/tree/main/packages/streaming-image-volume-loader/examples)
[Tools Example](https://github.com/cornerstonejs/cornerstone3D/tree/main/packages/tools/examples)

**Comment by 1009058470** [comment]
> Here are the examples: [Adapters Examples](https://github.com/cornerstonejs/cornerstone3D/tree/main/packages/adapters/examples) [Core Examples](https://github.com/cornerstonejs/cornerstone3D/tree/main/packages/core/examples) [DicomImageLoader Examples](https://github.com/cornerstonejs/cornerstone3D/tree/main/packages/dicomImageLoader/examples) [NiftiVolumeLoader Examples](https://github.com/cornerstonejs/cornerstone3D/tree/main/packages/nifti-volume-loader/examples) [StreamingImageVolumeLoader Examples](https://github.com/cornerstonejs/cornerstone3D/tree/main/packages/streaming-image-volume-loader/examples) [Tools Examples](https://github.com/cornerstonejs/cornerstone3D/tree/main/packages/tools/examples)
> 
> or
> 
> https://www.cornerstonejs.org/docs/examples

well but it can run ` yarn run example tools`
and then that will make me to select a example to run under it like this
```
PS D:\cornerstone3D\cornerstone3D-1.77.12\cornerstone3D-1.77.12> yarn run example tools        

=> Extract examples

 D:\cornerstone3D\cornerstone3D-1.77.12\cornerstone3D-1.77.12\packages\core\examples
 D:\cornerstone3D\cornerstone3D-1.77.12\cornerstone3D-1.77.12\packages\tools\examples
 D:\cornerstone3D\cornerstone3D-1.77.12\cornerstone3D-1.77.12\packages\streaming-image-volume-loader\examples
 D:\cornerstone3D\cornerstone3D-1.77.12\cornerstone3D-1.77.12\packages\dicomImageLoader\examples
 D:\cornerstone3D\cornerstone3D-1.77.12\cornerstone3D-1.77.12\packages\nifti-volume-loader\examples
 D:\cornerstone3D\cornerstone3D-1.77.12\cornerstone3D-1.77.12\packages\adapters\examples

=> Error: Did not find any examples matching tools
Did you mean any of these?


[28] segmentBidirectionalTool
[27] SculptorTool
[26] scaleOverlayTool
[25] planarFreehandROITool
[24] planarFreehandContourSegmentationTool
[23] multipleToolGroups
[22] magnifyTool
[21] labelmapToolGroupSpecificConfiguration
[20] dynamicCINETool
[19] CINETool
[18] annotationToolModes
[17] advancedMagnifyTool
[16] niftiWithTools
[15] volumeAnnotationTools
[14] videoTools
[13] videoSplineROITools
[12] stackManipulationToolsTouch
[11] stackManipulationTools
[10] stackAnnotationToolsSpecificConfiguration
[9] stackAnnotationTools
[8] splineROITools
[7] splineContourSegmentationToolsAdvanced
[6] splineContourSegmentationTools
[5] sharedToolState
[4] polyDataActorManipulationTools
[3] labelmapSegmentationTools
[2] doubleClickWithStackAnnotationTools
[1] calibrationTools
[Enter "exit" to quit]
Enter the number of the example you want to run:
```
![image](https://github.com/cornerstonejs/cornerstone3D/assets/30902531/824dcaa8-837f-4970-a1a9-445b6cf14ad7)

**Comment by 1009058470** [comment]
> ![image](https://private-user-images.githubusercontent.com/50026015/340103799-120c657f-17cf-4657-af68-6f4d5006ae07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDQ0NzIsIm5iZiI6MTcxODYwNDE3MiwicGF0aCI6Ii81MDAyNjAxNS8zNDAxMDM3OTktMTIwYzY1N2YtMTdjZi00NjU3LWFmNjgtNmY0ZDUwMDZhZTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA2MDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliY2Y5MmFkZmQzN2E5NzAwZTJjMDg2NWRlNTUyOGYyMmVhNzI0ZmFlODU3MDc3YTUyNmQ0NjZmNWFiMzE1MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P4PkyluQPgLNbOZOTkjQSVN-7uzHZj9tUT7N9VfD_uY)
> 
> For example, `yarn example stackBasic` or `yarn example stackApi`

to run that cmd, where i should in?
in the core example or the root path?

**Comment by sedghi** [comment]
at root
