### ISSUE TITLE
[Bug] The example of contourrendering cannot display contours on 3D

### ISSUE THREAD

**Issue by IrvingLu** [cornerstonejs/cornerstone3D#1343]
### Describe the Bug

The example of contourrendering cannot display contours on 3D
saw that the code for this example removed the 3D display, and I don't understand why it was removed. When I try to display the outline, I will report the following error：

undefined is not iterable (cannot read property Symbol(Symbol.iterator))
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at updateContourSets (http://localhost:3000/tutorial.js:136362:41)
    at handleContourSegmentation (http://localhost:3000/tutorial.js:136332:3)
    at Object.render (http://localhost:3000/tutorial.js:136241:105)
    at http://localhost:3000/tutorial.js:137342:44
    at Array.map (<anonymous>)
    at SegmentationDisplayTool.renderSegmentation (http://localhost:3000/tutorial.js:137327:75)
    at SegmentationRenderingEngine._triggerRender (http://localhost:3000/tutorial.js:156046:37)
    at http://localhost:3000/tutorial.js:155922:14

### Steps to Reproduce

Use the latest version

### The current behavior

 The example of contourrendering cannot display contours on 3D

### The expected behavior

Display contours on 3D

### OS

windows10

### Node version

1.61.5

### Browser

Chrome

**Comment by sedghi** [comment]
It was not removed really you still can render contour in 3D. if it does not work it is a bug, but for 2D rendering of contours you have to use the new svg based contour rendering

**Comment by IrvingLu** [comment]
感谢您的回复，它确实没有工作，我更新到了最新版本，现在报如下错误
![Uploading 20240701-135239.jpg…]()

**Comment by IrvingLu** [comment]
Not implemented
    at VolumeViewport3D.getSliceIndex (http://localhost:3000/tutorial.js:72716:11)
    at VolumeViewport3D.isReferenceViewable (http://localhost:3000/tutorial.js:65776:36)
    at http://localhost:3000/tutorial.js:152426:21
    at Array.filter (<anonymous>)
    at filterAnnotationsForDisplay (http://localhost:3000/tutorial.js:152419:22)
    at PlanarFreehandContourSegmentationTool.filterInteractableAnnotationsForElement (http://localhost:3000/tutorial.js:127574:92)
    at filterToolsWithAnnotationsForElement (http://localhost:3000/tutorial.js:110189:26)
    at HTMLDivElement.mouseMove (http://localhost:3000/tutorial.js:98146:119)
    at triggerEvent (http://localhost:3000/tutorial.js:92551:13)
    at HTMLDivElement.mouseMoveListener (http://localhost:3000/tutorial.js:100550:84)

**Comment by IrvingLu** [comment]
Thank you for your reply. It is indeed not working. I have updated it to the latest version and now it is reporting the following error：
![20240701-135239](https://github.com/cornerstonejs/cornerstone3D/assets/26640655/785bc5bc-c472-4cc5-b95c-45323d59d256)

**Comment by sedghi** [comment]
Can we take a step back? Please explain your use case. Why do you want to render contours in the 3D volume rendering?

**Comment by IrvingLu** [comment]
I want to show the contours like in the previous version，that's all for it
![img_v3_02cj_e55735c6-5652-4df8-abae-eabca083038g](https://github.com/cornerstonejs/cornerstone3D/assets/26640655/afe5836a-f8f1-4691-af62-a36fbc0ee753)

**Comment by sedghi** [comment]
The left view is already functioning in the current version. Is the right view what you need?

**Comment by IrvingLu** [comment]
yeah, the right side view is what I want to achieve

**Comment by IrvingLu** [comment]
> The left view is already functioning in the current version. Is the right view what you need?
yeah, the right side view is what I want to achieve
