### ISSUE TITLE
[Bug] Axial view on a volume not working on 2.0.0 beta

### ISSUE THREAD

**Issue by e-simpson** [cornerstonejs/cornerstone3D#1469]
### Describe the Bug

**The following issue is with the 2.0.0 beta running on Next.js as described in the [nextjs-cornerstone3d example repo](https://github.com/cornerstonejs/nextjs-cornerstone3d).**

When I try to load and view an axial view on a volume in orthographic mode it seems to break Cornerstone3D. Sagittal, coronal in orthographic mode and volume_3d mode work just fine. However, when I try to render the axial view and call `setVolumesForViewports`:
- it does not display (blank element view)
- the volume 3D view seems to break (preset not applied)
- In the console I see the error:
```
TypeError: Cannot destructure property 'imagePositionPatient' of '_metaData__WEBPACK_IMPORTED_MODULE_3__.get(...)' as it is undefined.
    at getClosestImageId (getClosestImageId.js:31:17)
    at VolumeViewport.getViewReference (VolumeViewport.js:354:110)
    at VolumeViewport.addActors (Viewport.js:197:34)
    at VolumeViewport.setActors (Viewport.js:166:14)
    at VolumeViewport._setVolumeActors (BaseVolumeViewport.js:669:14)
    at VolumeViewport.setVolumes (BaseVolumeViewport.js:513:14)
    at async eval (setVolumesForViewports.js:17:9)
    at async Promise.all (index 0)
    at async setVolumesForViewports (setVolumesForViewports.js:19:5)
    at async setup (testing.tsx:116:13)
```

I have tried loading both `wadouri:` and `wadors:` volumes.

### Steps to Reproduce

1. Clone [nextjs-cornerstone3d repo](https://github.com/cornerstonejs/nextjs-cornerstone3d)
2. Change [page.tsx line 60](https://github.com/cornerstonejs/nextjs-cornerstone3d/blob/6487663af31b6db9c7e3a59bea344569977dacec/app/page.tsx#L60) to `orientation: Enums.OrientationAxis.AXIAL,`
3. Change imageIds to `wadouri:` usage

### The current behavior

Blank view displays

### The expected behavior

Axial view renders

### OS

macOS 14.6.1

### Node version

20

### Browser

Chrome 126.0.6478.183

**Comment by e-simpson** [comment]
Note: editing details to better reflect Steps to Reproduce

**Comment by e-simpson** [comment]
It seems that this issue only occurs when using `wadouri:`. So this issue seems to be a duplicate of https://github.com/cornerstonejs/cornerstone3D/issues/958. 

I will close this now and reference there.
