### ISSUE TITLE
[Bug] crosshairs example error

### ISSUE THREAD

**Issue by kaizibaby** [cornerstonejs/cornerstone3D#774]
### Describe the Bug

It's an accidental event, refreshing 10 times may occur once。
-----------------------------------
macros.js:57 Error compiling shader '#version 300 es
#define attribute in
#define textureCube texture
#define texture2D texture
#define textureCubeLod textureLod
#define texture2DLod textureLod

#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
precision highp int;
#else
precision mediump float;
precision mediump int;
#endif

/*=========================================================================

  Program:   Visualization Toolkit
  Module:    vtkPolyDataVS.glsl

  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  All rights reserved.
  See Copyright.txt or http://www.kitware.com/Copyright.htm for details.

     This software is distributed WITHOUT ANY WARRANTY; without even
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
     PURPOSE.  See the above copyright notice for more information.

=========================================================================*/

attribute vec4 vertexDC;

out vec3 vertexVCVSOutput;
uniform mat4 PCVCMatrix;

uniform float dcxmin;
uniform float dcxmax;
uniform float dcymin;
uniform float dcymax;

void main()
{
  // dcsmall is the device coords reduced to the
  // x y area covered by the volume
  vec4 dcsmall = vec4(
    dcxmin + 0.5 * (vertexDC.x + 1.0) * (dcxmax - dcxmin),
    dcymin + 0.5 * (vertexDC.y + 1.0) * (dcymax - dcymin),
    vertexDC.z,
    vertexDC.w);
  vec4 vcpos = PCVCMatrix * dcsmall;
  vertexVCVSOutput = vcpos.xyz/vcpos.w;
  gl_Position = dcsmall;
}
': 
-----------------------------------------

macros.js:57 0: #version 300 es
1: #define attribute in
2: #define textureCube texture
3: #define texture2D texture
4: #define textureCubeLod textureLod
5: #define texture2DLod textureLod
6: 
7: 
8: #ifdef GL_FRAGMENT_PRECISION_HIGH
9: precision highp float;
10: precision highp int;
11: #else
12: precision mediump float;
13: precision mediump int;
14: #endif
15: 
16: /*=========================================================================
17: 
18:   Program:   Visualization Toolkit
19:   Module:    vtkPolyDataVS.glsl
20: 
21:   Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
22:   All rights reserved.
23:   See Copyright.txt or http://www.kitware.com/Copyright.htm for details.
24: 
25:      This software is distributed WITHOUT ANY WARRANTY; without even
26:      the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
27:      PURPOSE.  See the above copyright notice for more information.
28: 
29: =========================================================================*/
30: 
31: attribute vec4 vertexDC;
32: 
33: out vec3 vertexVCVSOutput;
34: uniform mat4 PCVCMatrix;
35: 
36: uniform float dcxmin;
37: uniform float dcxmax;
38: uniform float dcymin;
39: uniform float dcymax;
40: 
41: void main()
42: {
43:   // dcsmall is the device coords reduced to the
44:   // x y area covered by the volume
45:   vec4 dcsmall = vec4(
46:     dcxmin + 0.5 * (vertexDC.x + 1.0) * (dcxmax - dcxmin),
47:     dcymin + 0.5 * (vertexDC.y + 1.0) * (dcymax - dcymin),
48:     vertexDC.z,
49:     vertexDC.w);
50:   vec4 vcpos = PCVCMatrix * dcsmall;
51:   vertexVCVSOutput = vcpos.xyz/vcpos.w;
52:   gl_Position = dcsmall;
53: }
54: 

-----------------------------------------

VolumeMapper.js:365 Uncaught TypeError: Cannot read properties of null (reading 'isAttributeUsed')
    at publicAPI.setMapperShaderParameters (VolumeMapper.js:365:1)
    at publicAPI.updateShaders (VolumeMapper.js:354:1)
    at publicAPI.renderPieceDraw (VolumeMapper.js:919:1)
    at publicAPI.renderPiece (VolumeMapper.js:990:1)
    at publicAPI.volumePass (VolumeMapper.js:88:1)
    at publicAPI.apply (ViewNode.js:42:1)
    at publicAPI.traverse (ViewNode.js:29:1)
    at publicAPI.traverseVolumePass (Volume.js:44:1)
    at publicAPI.traverse (ViewNode.js:24:1)
    at publicAPI.traverse (ViewNode.js:32:1)
    
    
-------

### Steps to Reproduce

diocm files number >300
npm run example corsshiars
@cornerstonejs/core "version": "1.11.2",

### The current behavior

-

### The expected behavior

-

### OS

win10

### Node version

16.14.0

### Browser

chrome 116.0.5845.142

**Comment by kaizibaby** [comment]
Looks like the same bug as vtk.js ,how can I bypass this bug？
https://github.com/Kitware/vtk-js/issues/2866
