### ISSUE TITLE
[Bug] imageToWorldCoords does not work correctly

### ISSUE THREAD

**Issue by Whiled0S** [cornerstonejs/cornerstone3D#778]
### Describe the Bug

First of all, I need to mention that my original goal is to get transformation matrix/object for displayed image in canvas coordinate system. Other words, I need to get image position relatively to top left canvas corner in pixels, image scale (image width in pixels on canvas divide by original image width in pixels for scaleX and same logic with height for scaleY) and rotation. To calculate image position and scale I tried to use `imageToWorldCoords` method from `utilities` with `worldToCanvas` from my instance of `StackViewport`. It looks something like this:

```ts
function computePosition(viewport: Types.IStackViewport): Types.Point2 {
    const imageId = viewport.getCurrentImageId();

    const positionInImageCoordinates = [0, 0] as Types.Point2;
    const positionInWorldCoordinates = utilities.imageToWorldCoords(imageId, positionInImageCoordinates) as Types.Point3;

    return viewport.worldToCanvas(positionInWorldCoordinates);
}

function computeScale(viewport: Types.IStackViewport): { x: number, y: number } {
    const image = viewport.getCornerstoneImage();

    const topLeftImageCornerInImageCoordinates = [0, 0] as Types.Point2;
    const bottomRightImageCornerInImageCoordinates = [image.width, image.height] as Types.Point2;

    const topLeftImageCornerInWorldCoordinates = utilities.imageToWorldCoords(image.imageId, topLeftImageCornerInImageCoordinates) as Types.Point3;
    const bottomRightImageCornerInWorldCoordinates = utilities.imageToWorldCoords(image.imageId, bottomRightImageCornerInImageCoordinates) as Types.Point3;

    const [leftImageCoordinateInCanvas, topImageCoordinateInCanvas] = viewport.worldToCanvas(topLeftImageCornerInWorldCoordinates);
    const [rightImageCoordinateInCanvas, bottomImageCoordinateInCanvas] = viewport.worldToCanvas(bottomRightImageCornerInWorldCoordinates);

    const imageWidthInCanvas = rightImageCoordinateInCanvas - leftImageCoordinateInCanvas;
    const imageHeightInCanvas = bottomImageCoordinateInCanvas - topImageCoordinateInCanvas;

    const scaleX = imageWidthInCanvas / image.width;
    const scaleY = imageHeightInCanvas / image.height;

    return { x: scaleX, y: scaleY };
}

// `viewport` id defined here
viewportElement.addEventListener(Enums.Events.CAMERA_MODIFIED, () => {
    const position = computePosition(viewport);
    const scale = computeScale(viewport);
    const rotation = viewport.getRotation();

    // other code...
});
```

Unfortunately, this approach does not work because method `imageToWordCoords` from `utilities` throws this error:

```
bundle.js:40443 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Object.scaleAndAdd (bundle.js:40443:16)
    at Object.imageToWorldCoords (bundle.js:69289:18)
    at computePosition (bundle.js:108323:60)
    at HTMLDivElement.<anonymous> (bundle.js:108314:26)
    at triggerEvent (bundle.js:38048:15)
    at StackViewport.triggerCameraModifiedEventIfNecessary (bundle.js:85586:9)
    at StackViewport.setCamera (bundle.js:85574:12)
    at PanTool._dragCallback (bundle.js:100019:31)
    at PanTool.mouseDragCallback (bundle.js:100001:12)
    at HTMLDivElement.mouseDrag (bundle.js:106045:16)
```

I investigated original method and tried to make it work by myself, but this did not give me any result. To make long story short, i tried different series and t works on `CT` and `MR` modalities, but does not work on `DX` because column and row cosines are `null` and origin is `undefined`. I tried to make it default with something like `[0, 0, 0]` but it works wrong for now. Hope you can help me with this issue.

### Steps to Reproduce

1. Open DX/RG modality with cornerstone viewer and stack viewport (you can use my example file located here https://filetransfer.io/data-package/lxlqzF3M#link)
2. Run code above in your environment
3. See errors in console

### The current behavior

Code throws errors in console and you cannot get calculated values

### The expected behavior

It works fine like with CT/MR modalities

### OS

MacOS

### Node version

18.17.0

### Browser

Chrome version 116.0.5845.179 (Official Build) (arm64)

**Comment by vglsk** [comment]
I have the same problem, I don’t know how to solve it yet

**Comment by sgielen** [comment]
This seems to happen because the image plane has no `imagePositionPatient`, i.e. pixel positions on the image cannot be converted into world positions within the frame of reference.

Looking at the implementation of `imageToWorldCoords`:

```
  const imagePlaneModule = metaData.get('imagePlaneModule', imageId);
  // ...
  const {
    columnCosines,
    rowCosines,
    imagePositionPatient: origin, // <--- this is undefined
  } = imagePlaneModule;
  // ...
  vec3.scaleAndAdd(
    imageCoordsInWorld,
    origin, // <--- this is undefined
    rowCosines,
    // to accommodate the [0,0] being on the top left corner of the top left pixel
    // but the origin is at the center of the top left pixel
    rowPixelSpacing * (imageCoords[0] - 0.5)
  );
```

Here, `vec3.scaleAndAdd` is reading `origin[0]`, which is undefined, leading to the `Cannot read properties of undefined (reading '0')` exception.

I think the solution could be to give the image a unique frame of reference UID, and then fill in the ImagePositionPatient, so that the pixels on the image can be converted to a world position in a unique frame of reference.

**Comment by sgielen** [comment]
I believe the following metadata provider makes an (arguably ugly) start to this. It may need some adapting for other use-cases. When the `imagePlaneModule` metadata is requested for an image that does not have any, it creates a random new frame of reference UID (different every time) and sets some standard coordinates and orientations.

**This is just a workaround - I believe the fix should be in worldToImageCoords / imageToWorldCoords not assuming the image implements the plane module.**

```typescript
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import * as cornerstoneDicomImageLoader from '@cornerstonejs/dicom-image-loader'

// Add a metadata provider which ensures 3D image plane module definition
// even for 2D Mammography images.
// Work-around for https://github.com/cornerstonejs/cornerstone3D/issues/778.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const planeModuleProvider = (type: string, query: any): any => {
  if (type === 'imagePlaneModule') {
    const imagePlaneModule =
      cornerstoneDicomImageLoader.wadouri.metaData.metaDataProvider(
        type,
        query,
      );
    if (!imagePlaneModule.imagePositionPatient) {
      // Assume a frame of reference with origin 0, 0, 0.
      imagePlaneModule.frameOfReferenceUID =
        '2.999.' + (Math.random() * 1000000000).toFixed(0);
      imagePlaneModule.imagePositionPatient = [0, 0, 0];
      imagePlaneModule.imageOrientationPatient = [1, 0, 0, 0, 1, 0];
      imagePlaneModule.rowCosines = [1, 0, 0];
      imagePlaneModule.columnCosines = [0, 1, 0];
    }
    return imagePlaneModule;
  }
  return undefined;
};
cornerstone.metaData.addProvider(planeModuleProvider, 1000);
```

**Comment by sedghi** [comment]
What is your data, can you you share it? I wanna see how come it doesn't have orientations

**Comment by abustany** [comment]
@sedghi attached is a random XRay where I observe the same issue. It doesn't have any tags from the "Image Plane" DICOM module, because it's a CR and not a CT I suppose (but my understanding is quite limited).

[hand.dcm.zip](https://github.com/cornerstonejs/cornerstone3D/files/13494341/hand.dcm.zip)

**Comment by sedghi** [comment]
What are you doing? You want to use tools and it throws error?

**Comment by abustany** [comment]
agree, this is pretty much what was suggested in https://github.com/cornerstonejs/cornerstone3D/issues/778#issuecomment-1762857528 , and what I'm using in the meanwhile :+1:

**Comment by abustany** [comment]
Quick comment on the workaround proposed in https://github.com/cornerstonejs/cornerstone3D/issues/778#issuecomment-1762857528 : generating random `frameOfReferenceUID` confuses the re-rendering logic of annotation tools. I replaced the random value by the image ID itself, and things seem to work as expected.

**Comment by sedghi** [comment]
@abustany Can you create a PR then for us? thanks

**Comment by amszlk** [comment]
我用的新版本，这个问题好像还存在，，，，我在移植 overlayDataTool 的时候遇到的这个问题

**Comment by sgielen** [comment]
Cornerstone3D 2.0 requires a slight change to the hacky workaround provided in https://github.com/cornerstonejs/cornerstone3D/issues/778#issuecomment-1762857528:

```
    const planeModuleProvider = (type: string, query: any): any => {
      if (type === 'imagePlaneModule') {
        let imagePlaneModule =
          cornerstoneDicomImageLoader.wadouri.metaData.metaDataProvider(
            type,
            query,
          );
        if (!imagePlaneModule) {
          imagePlaneModule = {};
        }
        if (!imagePlaneModule.imagePositionPatient) {
          // Assume a frame of reference with origin 0, 0, 0.
          // See comment by @abustany - use image ID, which is not a valid UID,
          // but prevents confused annotations tools
          imagePlaneModule.frameOfReferenceUID = query;
          // alternatively, replace the frame of reference UID with a randomly generated UID:
          //imagePlaneModule.frameOfReferenceUID =
          //  '2.999.' + (Math.random() * 1000000000).toFixed(0);
          imagePlaneModule.imagePositionPatient = [0, 0, 0];
          imagePlaneModule.imageOrientationPatient = [1, 0, 0, 0, 1, 0];
          imagePlaneModule.rowCosines = [1, 0, 0];
          imagePlaneModule.columnCosines = [0, 1, 0];
        }
        return imagePlaneModule;
      }
      return undefined;
    };
```

**Comment by sedghi** [comment]
is this still an issue
